# Generated by Django 4.1.3 on 2022-11-03 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userdashboard', '0002_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('day_of_birth', models.IntegerField(default=0)),
                ('month_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('document_uploaded', models.CharField(blank=True, max_length=50, null=True)),
                ('year_issued', models.IntegerField(default=0)),
                ('verify_document', models.FileField(default='r.jpg', upload_to='verify_document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
