# Generated by Django 4.1.3 on 2022-11-03 20:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0003_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verification',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
    ]
