# Generated by Django 4.1.3 on 2022-11-04 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0004_verification_country_verification_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='userdashboard.profile')),
            ],
        ),
    ]
