# Generated by Django 4.1.3 on 2022-11-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0005_profile_referral_price_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_people',
            field=models.IntegerField(default=0),
        ),
    ]
