# Generated by Django 4.1.3 on 2022-11-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0006_profile_referral_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
